#!/usr/bin/env python3
"""
model-updater.py

This script consolidates steering documents into a single file that can be
passed to your models. It also injects a black‑box contract and other
guardrails into each task file generated by the Specify CLI. Run this
script whenever you update your steering documents or generate new
tasks to ensure they all conform to the project’s conventions.

Usage:
    python3 orchestrator/model-updater.py <feature_id>

If <feature_id> is omitted, the script will attempt to update tasks for
all features in the `specs/` directory.
"""

import sys
import re
from pathlib import Path


def read_file(path: Path) -> str:
    try:
        return path.read_text()
    except FileNotFoundError:
        return ""

def inject_guardrails(text: str, foundation: str) -> str:
    """Inject the foundation into a task file if not present."""
    if "Black‑Box Contract" not in text:
        return foundation + "\n" + text
    return text

def update_tasks(feature_id: str | None) -> int:
    """Walk task files and insert guardrails. Return number of updated files."""
    base_dir = Path("specs")
    foundation = read_file(Path("steering/00-foundation.md"))
    updated = 0
    for feature in base_dir.iterdir():
        if not feature.is_dir():
            continue
        if feature_id and feature.name != feature_id:
            continue
        tasks_dir = feature / "tasks"
        if not tasks_dir.exists():
            continue
        for task in tasks_dir.glob("*.md"):
            content = task.read_text()
            new_content = inject_guardrails(content, foundation)
            if new_content != content:
                task.write_text(new_content)
                updated += 1
    return updated

def consolidate_steering(owner: str = "", repo: str = "", feature: str = "") -> Path:
    """Create a single unified steering file from individual docs."""
    target = Path("steering/_ACTIVE.md")
    lines: list[str] = []
    lines.append(f"# Steering\n\nRepo: `{owner}/{repo}` | Feature: `{feature}`\n")
    lines.append("## Core Doctrine\n")
    lines.append(read_file(Path("steering/00-foundation.md")))
    lines.append("\n## Per-Model Addenda\n")
    for model in ["codex", "claude", "gemini"]:
        lines.append(f"\n### {model.upper()}\n")
        lines.append(read_file(Path("steering/models") / f"{model}.md"))
    target.write_text("\n".join(lines))
    return target

def main() -> None:
    feature_id = sys.argv[1] if len(sys.argv) > 1 else None
    updated = update_tasks(feature_id)
    cfg_path = Path("orchestrator/config.yaml")
    owner = ""; repo = ""; feature = feature_id or ""
    if cfg_path.exists():
        import yaml  # lazy import
        cfg = yaml.safe_load(cfg_path.read_text())
        owner = cfg.get("owner", "")
        repo = cfg.get("repo", "")
        if not feature:
            feature = cfg.get("feature_branch", "")
    path = consolidate_steering(owner, repo, feature)
    print(f"Updated {updated} task file(s). Unified steering written to {path}")

if __name__ == "__main__":
    main()